### ISSUE TITLE
Add Option to View all Posts by a Given User...

### ISSUE THREAD

**Issue by datahead8888** [Quintus/chessboard#12]
It would be useful to have an option to view all posts by a user.  This is useful sometimes for searching for a user's post.  It should be accessible from the view profile screen.

**Comment by Quintus** [comment]
Isn’t the search function good enough for that? Try clicking "search" on the top bar and enter the author’s name in the author field. That should do the trick.

Vale,
Quintus

**Comment by Luiji** [comment]
A shortcut from the user's profile to that search may be useful anyway.

**Comment by Quintus** [comment]
> A shortcut from the user's profile to that search may be useful anyway.

Certainly doable.
