### ISSUE TITLE
"[show]" Button for Videos

### ISSUE THREAD

**Issue by Luiji** [Quintus/chessboard#2]
A nice little feature that 4chan has in their software that we might want to consider ripping off, we can have the forum automatically detect YouTube/Vimeo/etc. links and place a little `[show]` link after it that, when clicked, embeds the video right below it so you don't have to leave the website to view a lot of videos.

I got the idea after seeing the cat video thread on the TSC forums.

It would be implemented using JavaScript and, in the case JavaScript wasn't detected, the link shouldn't even be visible. The forum software would just generate something like:

```
<a href="...">youtube link...</a> <a class="youtube-link" data-url="..."></a>
```

Then there'd be a little JavaScript that searches through every `<a>` with the class `youtube-link`, add an `onclick` event, and fill in the text with `[show]`.

If you guys are into this I could probably implement it myself.

**Comment by Quintus** [comment]
Closing as I don't maintain this anymore.
